spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: resource-processor

server:
  port : 8081

queue:
  processing-queue: PROCESSING_QUEUE

service:
  resource.endpoint: http://api-gateway:8090/resource-service
  song.endpoint: http://api-gateway:8090/song-service

feign:
  retryAttempts: 5
  retryPeriod: 2000

eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/